package com.heesungum.customkeyboard

const val QWERTY_KEYPAD_COLUMN = 5

const val NUMBER_LINE = 10

const val QWERTY_FIRST_LINE = 10
const val QWERTY_FIRST_LINE_START_POSITION = 10
const val QWERTY_FIRST_LINE_END_POSITION = 19

const val QWERTY_SECOND_LINE = 9
const val QWERTY_SECOND_LINE_START_POSITION = 20
const val QWERTY_SECOND_LINE_END_POSITION = 28

const val QWERTY_THIRD_LINE = 9
const val QWERTY_THIRD_LINE_START_POSITION = 29
const val QWERTY_THIRD_LINE_END_POSITION = 37

const val QWERTY_FORTH_LINE = 6
const val QWERTY_FORTH_LINE_START_POSITION = 38
const val QWERTY_FORTH_LINE_END_POSITION = 43